services:
  app:
    image: ${ECR_REPOSITORY}
    container_name: fitness-tracker-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
